### ISSUE TITLE
Erro ao rodar o comando yarn prod

### ISSUE THREAD

**Issue by ghost** [douglaszuqueto/esp8266-rfid-banco-de-dados#1]
Boa Tarde Douglas! 

Parabéns pelo excelente trabalho que apesar de simples, como vc diria, para mim não é nada simples. 

Rodei tudo conforme vc indicou, instalei os programas indicados tb. Estou utilizando a versão Ubuntu 16.04. 

Quando fui executar o comando **_yarn prod_**, aparece o seguinte erro no terminal: 

![captura de tela de 2017-06-07 12-49-34](https://user-images.githubusercontent.com/25107890/26888124-710ed078-4b80-11e7-8a4c-c10c09db1347.png)

Como posso proceder para rodar a aplicação? 

Obrigado , parabens novamente pelo projeto,
Atenciosamente,
Rogério

**Comment by douglaszuqueto** [comment]
Olá @RogerioCassares , pelo que percebi, faltou 1 passo anterior, que se trata deste cara aqui: https://github.com/douglaszuqueto/esp8266-rfid-banco-de-dados#instalando-as-dependências

Basicamente, dando o comando yarn, fará com que instale as dependências que são utilizadas pela aplicação :)

E muitíssimo obrigado pelo feedback <3. Espero estar contribuindo de alguma forma.

Grande Abraço

**Comment by ghost** [comment]
Olá Douglas, novamente eu :|

Já havia rodado o comando yarn, mas rodei novamente e pareceu que algo mudou. Posteriormente executei o yarn product e apareceu a seguinte mensagem de erro:

![captura de tela de 2017-06-07 13-15-04](https://user-images.githubusercontent.com/25107890/26889150-8af6c2d6-4b83-11e7-9c38-f714ae9bdb5f.png)

No tutorial vc disse: _**

> Para centralizar de uma forma bacana as variáveis de nosso ambiente, eu utilizei o **_dotenv_** para este fim.

**_

É necessário instalar o dotenv em algum ponto?  do procedimento? 

Obrigado novamente 
Abraços!

**Comment by douglaszuqueto** [comment]
@RogerioCassares , agora está tudo normal.

O problema agora, é que você precisa ter um banco de dados rodando na sua máquina. Perceba o erro - não foi possível conectar em localhost na porta 3306.

Logo, você deverá ter de instalar e configurar de acordo com sua vontade. No caso, o padrão é o próprio localhost e usando a porta padrão. Caso, seu banco de dados, rode em outra máquina ou em outra porta terá de mudar os parâmetros do .env.
