### ISSUE TITLE
MQTT broker <--> Banco de dados - customizado

### ISSUE THREAD

**Issue by ghost** [douglaszuqueto/esp8266-rfid-banco-de-dados#2]
Olá Douglas, sou eu novamente. Tenho uma dúvida de como utilizar a aplicação. Se vc pudesse me ajudar seria incrível! 

Tenho uma aplicação local rodando um MQTT broker. É possível utilizar a aplicação de servidor, banco de dados e _front-end_ que vc criou e adaptar à minha? 

Que parâmetros eu deveria modificar? Somente o arquivo **_.env_** seria o bastante? 

Desde já agradeço a sua atenção desprendida a responderme e parabéns pelo serviço realizado em prol da comunidade!

Abraços,
Rogério Cassares

**Comment by douglaszuqueto** [comment]
Olá @RogerioCassares . Então, tudo dependerá do seu real necessário. Se vai usar um broker seu, é só mudar as variáveis pertinentes. 

Banco de dados mesma coisa, e assim por diante.

Por isso tentei reunir todas variáveis de ambiente em um arquivo só. Para ficar mais simples, fácil, amigável e customizável caso as pessoas queiram trocar ou estender a outro ambiente.

Abraços.
