### ISSUE TITLE
Funcionamento através de máquina virtual box - vagrantfile

### ISSUE THREAD

**Issue by ghost** [douglaszuqueto/esp8266-rfid-banco-de-dados#5]
Bom dia Douglas! Como estás?

Estou tentando rodar as páginas html através de uma máquina virtual (guest) e visualizá-las em meu PC (host). Através do servidor apache2. Em meu PC deu tudo certo! Parabéns pelo excelente trabalho! 

Mas rodando exatamente da mesma maneira na máquina virtual, o server aparece como conectado, rodando o comando "yarn prod" perfeitamente. As configurações do ambiente em ".env" também estão aplicadas corretamente! o banco de dados mysql. também está guardando as informações. mas quando abro a página html no host parece que as páginas não conseguem acessar o banco de dados  que estão dentro da máquina virtual! Aparece somente os cabeçalhos, porém nenhuma informação. Será que vc conseguiria me ajudar, por favor? 

Átravés do arquivo vagrant já liberei as portas do firewall linux mysql e do apache para conversar com meu PC. mas o problema creio que seja em algum lugar entre html e banco de dados . Já tentei diversas maneiras mas nada dá certo, por enquanto. 

Muito obrigado pelo auxílio, 
Atenciosamente, 
Rogério.

**Comment by douglaszuqueto** [comment]
Ola @RogerioCassares - desculpe pela demora do retorno.

Então, teria que ver como está seu cenário ai. Talvez algo esteja se perdendo na comunicação http - quando a aplicação web requisita ao webservice os respectivos dados(tags, users e logs).
